name: build rootfs

on:
  push:
    branches: [ 'master' ]
    paths:
      - 'build.sh'
      - 'config/**'
      - 'version.txt'
      - '.github/**'
  pull_request:
    branches: [ 'master' ]
    paths:
      - 'build.sh'
      - 'config/**'
      - 'version.txt'
  workflow_dispatch:

jobs:
  build:
    name: Build tar file
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-codeql: 'true'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: update source and add binfmts # 更新源到 noble
        run: |
          sudo sed -i 's/jammy/noble/g' /etc/apt/sources.list
          sudo apt update -y && sudo apt install mmdebstrap qemu-user-static usrmerge qemu-user systemd
          sudo apt-mark hold usrmerge
          sudo cp -v /usr/lib/arch-test/riscv64 /usr/lib/arch-test/loong64
          sudo sed -i "/riscv64  => 'riscv64',/a\            loong64  => 'loongarch64'," /usr/bin/mmdebstrap
          sudo systemctl restart systemd-binfmt

      - name: Run build.sh
        run: |
          sudo bash build.sh

      - name: Read version
        id: read_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Upload build files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rootfs-files
          path: |
            rootfs/openkylin-rootfs-amd64.img
            rootfs/openkylin-rootfs-arm64.img
            rootfs/openkylin-rootfs-riscv64.img
